# Generated by Django 4.2.15 on 2024-09-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandData',
        ),
    ]
